-- Last updated: 8/11/2026, 2:21:42 PM
# Write your MySQL query statement below
SELECT MAX(SALARY) AS SECONDHIGHESTSALARY 
FROM EMPLOYEE WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEE);
-- ORDER BY SALARY DESC LIMIT 1;